import os

class Standard:
    holder = dict()
    ranges = []

    def setDiscretization(self, value):
        self.fieldAdder("ho spatial discretization",value)
    def setEigenvalueProblem(self, value):
        self.fieldAdder("do eigenvalue calculations",value)
    def setFEPolynomialDegree(self, value):
        self.fieldAdder("finite element polynomial degree",value)
    def setFirstThermalGroup(self, value):
        self.fieldAdder("thermal group boundary",value)
    def setHaveReflectiveBC(self, value):
        self.fieldAdder("have reflective boundary",value)
    def setNCells(self, value):
        self.fieldAdder("number of cells for x, y, z directions",value)
    def setNEnergyGroups(self, value):
        self.fieldAdder("number of groups",value)
    def setOutputFilenameBase(self, value):
        self.fieldAdder("output file name base",value)
    def setReflectiveBoundary(self, value):
        self.fieldAdder("reflective boundary names",value)
    def setSpatialDimension(self, value):
        self.fieldAdder("problem dimension",value)
    def setSpatialMax(self, value):
        self.fieldAdder("x, y, z max values of boundary locations",value)
    def setTransportModel(self, value):
        self.fieldAdder("transport model",value)

    # Mesh
    def setMeshGenerated(self, value):
        self.fieldAdder("is mesh generated by deal.II",value)
    def setMeshFilename(self, value):
        self.fieldAdder("mesh file name",value)
    def setUniformRefinements(self, value):
        self.fieldAdder("uniform refinements",value)
    def setFuelPinRadius(self, value):
        self.fieldAdder("fuel Pin radius",value)
    def setFuelPinTriangulation(self, value):
        self.fieldAdder("triangulation type of fuel Pin",value)
    def setMeshPinResolved(self, value):
        self.fieldAdder("is mesh pin-resolved",value)

    # Material Parameters
    def setMaterialSubsection(self, value):
        self.fieldAdder("material ID map",value)
    def setMaterialMapFilename(self, value):
        self.fieldAdder("material id file name",value)
    def setMaterialFilenames(self, value):
        self.fieldAdder("material id file name map",value)
    def setNumberOfMaterials(self, value):
        self.fieldAdder("number of materials",value)
    def setFuelPinMaterialMapFilename(self, value):
        self.fieldAdder("fuel pin material id file name",value)

    # Acceleration Parameters
    def setPreconditioner(self, value):
        self.fieldAdder("ho preconditioner name",value)
    def setBSSOR_Factor(self, value):
        self.fieldAdder("ho ssor factor",value)
    def setDoNDA(self, value):
        self.fieldAdder("do nda",value)
    def setNDA_Discretization(self, value):
        self.fieldAdder("nda spatial discretization",value)
    def setNDALinearSolver(self, value):
        self.fieldAdder("nda linear solver name",value)
    def setNDAPreconditioner(self, value):
        self.fieldAdder("nda preconditioner name",value)
    def setNDA_BSSOR_Factor(self, value):
        self.fieldAdder("nda ssor factor",value)

    # Solvers
    def setEigenSolver(self, value):
        self.fieldAdder("eigen solver name",value)
    def setInGroupSolver(self, value):
        self.fieldAdder("in group solver name",value)
    def setLinearSolver(self, value):
        self.fieldAdder("ho linear solver name",value)
    def setMultiGroupSolver(self, value):
        self.fieldAdder("mg solver name",value)

    # Angular Quadrature
    def setAngularQuad(self, value):
        self.fieldAdder("angular quadrature name",value)
    def setAngularQuadOrder(self, value):
        self.fieldAdder("angular quadrature order",value)


    def fieldAdder(self,field,value):
        if type(value) is list: # you input a range of values for one 
            self.ranges.append((field, value))
        else:
            self.holder[field] = value
    
    def snapshot(self):
        for i in self.holder:
             print(str(i) + " = " + str(self.holder[i]))
        print(str(self.ranges[0][0]) + " = " + str(self.ranges[0][1]))

    def saveAs(self, pathname): 
        temp = pathname.split("/")
        directories, filename = "/".join(temp[:-1])+"/", temp[-1]
        try:
            os.mkdir(directories)
        except FileExistsError:
            pass
        if len(self.ranges) > 0:
            if len(self.ranges) > 1:
                print("Error—only try inputting one range right now")
            else:
                print(self.ranges[0][1])
                for i in range(len(self.ranges[0][1])):
                    currFile = directories + filename+"-"+str(i)+".input"
                    print(currFile)
                    with open(currFile,"w") as file:
                        for j in self.holder:
                            file.write(j+ " = " + str(self.holder[j])+ "\n")


                        file.write(self.ranges[0][0] + " = " + str(self.ranges[0][1][i]) + "\n")
        else:
            with open(directories + filename+".input","w") as file:
                for i in self.holder:
                    file.write(i + " = " + str(self.holder[i]) + "\n")
        print("Files saved to " + pathname)